import cv2
import numpy as np


img=cv2.imread('C:\\Users\\haoyu\\Desktop\\di.png')
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
kernel = np.ones((3,3),np.uint8)
dige_erosion = cv2.erode (img, kernel,iterations = 2)
cv2.imshow('erosion',dige_erosion)
cv2.waitKey(0)
cv2.destroyAllWindows ()
kernel=np.ones((3,3),np.uint8)
dige_dilate = cv2.dilate (dige_erosion, kernel, iterations = 1)
cv2.imshow('dilate',dige_dilate)
cv2.waitKey(0)
cv2.destroyAllWindows()
pie=cv2.imread('C:\\Users\\haoyu\\Desktop\\opencvimg\\origin\\pie.png')
cv2.imshow('pie',pie)
cv2.waitKey(0)
cv2.destroyAllWindows ()
kernel=np.ones((30,30),np.uint8)
erosion_1 = cv2.dilate(pie,kernel,iterations=1)
erosion_2 = cv2.dilate(pie,kernel,iterations=2)
erosion_3 = cv2.dilate(pie,kernel,iterations=3)
res=np.hstack((erosion_1,erosion_2,erosion_3))
cv2.imshow('res', res)
cv2.waitKey(0)
cv2.destroyAllWindows()